name: Checkov JSON Scan

on:
  workflow_call:

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}   # Get the caller repo not current repo by default
          ref: ${{ github.ref }}

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov and generate JSON
        continue-on-error: true
        run: |
          checkov -d . \
            -o json \
            --output-file checkov-results.json || true

      - name: Show Checkov summary
        run: |
          echo "### âœ… Checkov Security Scan Summary" >> $GITHUB_STEP_SUMMARY

          jq -r '
            [
              .results.failed_checks[]? | {
                check_id,
                check_name,
                file_path,
                resource,
                severity,
                guideline
              }
            ] 
            | group_by(.severity)
            | map({
                severity: .[0].severity,
                count: length
              }) 
            | (["Severity", "Count"], ["---", "---"]) + 
              map([.severity, (.count | tostring)])
            | @tsv' results_json.json | column -t -s $'\t' >> $GITHUB_STEP_SUMMARY

          echo "" >> $GITHUB_STEP_SUMMARY

          jq -r '
            [
              .results.failed_checks[]? | {
                check_id,
                check_name,
                file_path,
                resource,
                severity
              }
            ]
            | (["ID", "Severity", "File", "Resource"], ["--", "--", "--", "--"]) + 
              map([.check_id, .severity, .file_path, .resource])
            | @tsv' results_json.json | column -t -s $'\t' >> $GITHUB_STEP_SUMMARY



      - name: Upload Checkov JSON as artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-results-json
          path: checkov-results.json