name: Checkov JSON Scan

on:
  workflow_call:

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}   # Get the caller repo not current repo by default
          ref: ${{ github.ref }}

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov and generate JSON
        continue-on-error: true
        run: |
          checkov -d . \
            -o json \
            --output-file checkov-results.json || true

      - name: Show Checkov summary
        run: |
          echo "### âœ… Checkov Security Scan Summary" >> $GITHUB_STEP_SUMMARY

          if jq -e '.results.failed_checks | length > 0' checkov-results.json > /dev/null; then
            jq -r '
              [.results.failed_checks[]? | .severity]
              | group_by(.)
              | map({(.[0]): length})
              | add
              | to_entries
              | ["| Severity | Count |", "|----------|-------|"] + 
                map("| \(.key) | \(.value) |")
              | .[]
            ' checkov-results.json >> $GITHUB_STEP_SUMMARY

            echo "" >> $GITHUB_STEP_SUMMARY

            echo "#### ðŸ” Failed Checks Summary" >> $GITHUB_STEP_SUMMARY
            jq -r '
              [.results.failed_checks[]? | {id: .check_id, file: .file_path}]
              | unique
              | ["| Check ID | File |", "|----------|------|"] +
                map("| \(.id) | \(.file) |")
              | .[]
            ' checkov-results.json >> $GITHUB_STEP_SUMMARY
          else
            echo "âœ… No failed checks found." >> $GITHUB_STEP_SUMMARY
          fi



      - name: Upload Checkov JSON as artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-results-json
          path: checkov-results.json