jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }} # pulls the branch of the repo that triggered the reusable workflow
          ref: ${{ github.ref }}

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov and generate JSON
        continue-on-error: true
        run: |
          checkov -d . \
            --output-format json \
            --output-file-path checkov-results.json || true

      - name: Upload Checkov JSON as artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-results-json
          path: checkov-results.json
