name: Checkov JSON Scan

on:
  workflow_call:

jobs:
  checkov:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout caller repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}   # Get the caller repo not current repo by default
          ref: ${{ github.ref }}

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkov and generate JSON
        continue-on-error: true
        run: |
          checkov -d . \
            -o json \
            --output-file checkov-results.json || true

      - name: Show Checkov summary
        run: |

          echo "### âœ… Checkov Security Scan Summary" >> "$GITHUB_STEP_SUMMARY"


          jq -r '
            # Flatten to a list of failed checks
            .[]?                                    # each check-type block
            | .results.failed_checks[]?             # each failed check
            | .severity // "UNKNOWN"                # default when severity is null
          ' checkov-results.json \
          | sort \
          | uniq -c \
          | awk '
              BEGIN  { printf "| Severity | Count |\n|----------|-------|\n" }
              { printf "| %s | %d |\n", $2, $1 }
            ' >> "$GITHUB_STEP_SUMMARY"


          echo -e "\n### ðŸ› ï¸ Failed Checks Detail\n" >> "$GITHUB_STEP_SUMMARY"
          echo '|  Type | Check name | File | Lines |' >> "$GITHUB_STEP_SUMMARY"
          echo '|---------|---------------|---------|----------|' >> "$GITHUB_STEP_SUMMARY"

          jq -r '
            .[]?                                # each check-type block
            | .check_type as $ctype             # save the type
            | .results.failed_checks[]?         # each failed check
            | {
                type:   $ctype,
                name:   (.check_name | gsub("[\\r\\n]+";" ") | gsub("\\|";" ")),
                file:   .file_path,
                lines:  (.file_line_range // [] | map(tostring) | join("-"))
              }
            | [.type, .name, .file, .lines]     # emit as TSV
            | @tsv
          ' checkov-results.json |
          while IFS=$'\t' read -r type name file lines; do
            echo "| $type | $name | $file | $lines |" >> "$GITHUB_STEP_SUMMARY"
          done




      - name: Upload Checkov JSON as artifact
        uses: actions/upload-artifact@v4
        with:
          name: checkov-results-json
          path: checkov-results.json



      - name: Fail if vulnerabilities found
        run: |
          checkov -d . 

