name: Reusable ScanCode Logic

on:
  workflow_call: 

jobs:
  scan-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install ScanCode Toolkit
        run: |
          pip install --upgrade pip setuptools wheel
          pip install scancode-toolkit

      - name: Run ScanCode
        run: |
          scancode -clip --json-pp scancode-results.json .

      - name: Upload Scan Results
        uses: actions/upload-artifact@v4
        with:
          name: scan-results-artifact
          path: scancode-results.json
          retention-days: 5