name: checkov + trivy combined 

on:
  push:
    branches:
      - '**'
  workflow_call:

permissions:
  contents: read
  pull-requests: write
  security-events: write  # for Sarif upload


jobs:
  checkov-scan:
    uses: ./.github/workflows/checkov.yaml

  trivy-scan:
    uses: ./.github/workflows/trivy.yaml    