name: checkov + trivy combined

on:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  checkov-scan:
    uses: ./.github/workflows/checkov.yaml
    with:
      checkout: caller

  trivy-scan:
    uses: ./.github/workflows/trivy.yaml
    with:
      checkout: caller
